# -*- coding: utf-8 -*-
"""dia 10 atvd

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ttJ_9EEJXDnFkAlQoPBl3JN1r2HkjT4O
"""

print("Bem vindo a academia START STRONG")
while True:
    opcao = input("Deseja continuar com o cadastro com:\n1 - CPF\n2 - CNPJ\nDigite a opção desejada:")

    if opcao == "1":

        cpf=int (input("Digite seu cnpj:"))
        nome=input("Digite seu nome:")
        email=input("Digite seu email:")
        senha=input("Digite sua senha:")
        telefone=input("Digite seu telefone:")
        print("\n Cadastro realizado com sucesso!")
        print(f"Nome: {nome}\nCPF: {cpf}\nE-mail: {email}\nTelefone: {telefone}")

        idade = int(input("Digite sua idade: "))
        peso = float(input("Digite seu peso em KG: "))
        altura = float(input("Digite sua altura em metros: "))
        objetivo = input("Digite seu objetivo na academia: ")
        print("NOME",nome)
        print("CPF",cpf)
        print("IDADE",idade)
        print("PESO",peso,"KG")
        print("ALTURA",altura,"m")
        print("OBJETIVO",objetivo)

    elif opcao == "2":

        cnpj=int (input("Digite seu cnpj:"))
        razaosocial=input("Digite sua Razão Social:")
        nome_empresa=input("Digite seu nome:")
        email=input("Digite seu email:")
        senha=input("Digite sua senha:")

    else:
        print("\nOpção invalida! Por Favor , digite 1 para CPF ou 2 para CNPJ.")
        continue

